function onCreatePost()
makeAnimatedLuaSprite('tvStaticLeft', 'trashAlley/K1LL3R/tv_static_assets', -230, 1155)
addLuaSprite('tvStaticLeft', false)
addAnimationByIndices('tvStaticLeft', 'static', 'static anim', '0, 2', 24, true)
setScrollFactor('tvStaticLeft',0.99,0.99)
setProperty('tvStaticLeft.visible', false)
scaleObject('tvStaticLeft', 1, 1)

makeAnimatedLuaSprite('tvStaticRight', 'trashAlley/K1LL3R/tv_static_assets', 1250, 1175)
addLuaSprite('tvStaticRight', false)
addAnimationByIndices('tvStaticRight', 'static', 'static anim', '1, 3', 24, true)
setScrollFactor('tvStaticRight',0.99,0.99)
setProperty('tvStaticRight.visible', false)
scaleObject('tvStaticRight', 1, 1)

makeLuaSprite('warningScreen', 'trashAlley/K1LL3R/screen_danger', -120, 1300)
addLuaSprite('warningScreen', false)
setProperty('warningScreen.alpha', 0)
setProperty('warningScreen.angle', 0.5)
setScrollFactor('warningScreen',0.99,0.99)

makeLuaSprite('blueScreen', 'trashAlley/BLU3/blue_screens', -120, 1300)
addLuaSprite('blueScreen', false)
setProperty('blueScreen.alpha', 0)
setScrollFactor('blueScreen',0.99,0.99)

makeAnimatedLuaSprite('wall', 'trashAlley/M4N4G3R5/wallManager', -726, 650)
addLuaSprite('wall', false)
addAnimationByPrefix('wall', 'Killer', 'wall-Killer', 1, true)
addAnimationByPrefix('wall', 'Blue', 'wall-Blue', 1, true)
addAnimationByPrefix('wall', 'Red', 'wall-Red', 1, true)
addAnimationByPrefix('wall', 'Normal', 'wall-Normal', 1, true)
setScrollFactor('wall',0.99,0.99)
scaleObject('wall', 1, 1)

makeAnimatedLuaSprite('lightOverlay', 'trashAlley/M4N4G3R5/gradientManager', -726, 650)
addLuaSprite('lightOverlay', true)
addAnimationByPrefix('lightOverlay', 'Killer', 'overlay-Killer', 1, true)
addAnimationByPrefix('lightOverlay', 'Blue', 'overlay--Blue', 1, true)
addAnimationByPrefix('lightOverlay', 'Red', 'overlay-Red', 1, true)
addAnimationByPrefix('lightOverlay', 'Normal', 'overlay-Normal', 1, true)
setScrollFactor('lightOverlay',0.99,0.99)
setProperty('lightOverlay.alpha', 1)
setBlendMode('lightOverlay', 'ADD');
scaleObject('lightOverlay', 1, 1)

makeAnimatedLuaSprite('tvLights', 'trashAlley/K1LL3R/tv_lights_assets', 150, 950)
addLuaSprite('tvLights', true)
addAnimationByPrefix('tvLights', 'Killer', 'tv lights animated', 24, true)
addAnimationByPrefix('tvLights', 'Blue', 'blue', 24, true)
addAnimationByPrefix('tvLights', 'Red', 'red', 24, true)
addAnimationByPrefix('tvLights', 'Normal', 'tv lights animated', 24, true)
setScrollFactor('tvLights',0.99,0.99)
setProperty('tvLights.alpha', 0)
scaleObject('tvLights', 2, 2,false)

makeAnimatedLuaSprite('TVFront', 'trashAlley/M4N4G3R5/fgManager', -230, 1850)
addLuaSprite('TVFront', true)
addAnimationByPrefix('TVFront', 'Killer', 'tvFront-Killer', 1, true)
addAnimationByPrefix('TVFront', 'Blue', 'tvFront-Blue', 1, true)
addAnimationByPrefix('TVFront', 'Red', 'tvFront-Red', 1, true)
addAnimationByPrefix('TVFront', 'Normal', 'tvFront-Normal', 1, true)
setScrollFactor('TVFront',1.35,1.35)
scaleObject('TVFront', 1, 1)
end

function onUpdate(e)
setObjectOrder('TVFront',getObjectOrder('TVFront') + 10)
end